In [1]:
# pip install -e .
import pandas as pd
import numpy as np

import stfind as sf
from stfind.buildkernel import spatialkernel, isPD, buildchol, nearestPD

In [2]:
dir="../data/"

In [3]:
exprs = pd.read_csv(f'{dir}/example_exp.csv.gz', index_col=0)
exprs

6800STDY12499411_AAACAAGTATCTCCCA-1  \
HES4                                1.934841   
ISG15                               1.090409   
AGRN                                1.704291   
SDF4                                1.429758   
UBE2J2                              0.645860   
...                                      ...   
ATP6AP1                             0.645860   
GDI1                                1.429758   
FAM50A                              1.704291   
FAM3A                               1.090409   
FUNDC2                              0.645860   

         6800STDY12499411_AAACACCAATAACTGC-1  \
HES4                                0.000000   
ISG15                               0.000000   
AGRN                                0.000000   
SDF4                                0.000000   
UBE2J2                              1.987058   
...                                      ...   
ATP6AP1                             0.000000   
GDI1                                0.000000   
FAM50A                              0.000000   
FAM3A                               0.000000   
FUNDC2                              2.792554   

         6800STDY12499411_AAACATGGTGAGAGGA-1  \
HES4                                0.000000   
ISG15                               0.000000   
AGRN                                1.501834   
SDF4                                1.501834   
UBE2J2                              1.501834   
...                                      ...   
ATP6AP1                             1.501834   
GDI1                                1.501834   
FAM50A                              0.000000   
FAM3A                               0.000000   
FUNDC2                              1.501834   

         6800STDY12499411_AAACCGGGTAGGTACC-1  \
HES4                                0.000000   
ISG15                               0.000000   
AGRN                                2.144562   
SDF4                                1.438713   
UBE2J2                              1.438713   
...                                      ...   
ATP6AP1                             0.000000   
GDI1                                0.000000   
FAM50A                              0.000000   
FAM3A                               0.000000   
FUNDC2                              1.438713   

         6800STDY12499411_AAACCGTTCGTCCAGG-1  \
HES4                                0.000000   
ISG15                               2.311804   
AGRN                                3.158672   
SDF4                                0.000000   
UBE2J2                              2.311804   
...                                      ...   
ATP6AP1                             0.000000   
GDI1                                0.000000   
FAM50A                              2.311804   
FAM3A                               0.000000   
FUNDC2                              0.000000   

         6800STDY12499411_AAACGAAGATGGAGTA-1  \
HES4                                0.000000   
ISG15                               2.764867   
AGRN                                0.000000   
SDF4                                0.000000   
UBE2J2                              0.000000   
...                                      ...   
ATP6AP1                             0.000000   
GDI1                                0.000000   
FAM50A                              0.000000   
FAM3A                               0.000000   
FUNDC2                              0.000000   

         6800STDY12499411_AAACGAGACGGTTGAT-1  \
HES4                                0.000000   
ISG15                               0.720820   
AGRN                                2.772534   
SDF4                                2.469061   
UBE2J2                              0.000000   
...                                      ...   
ATP6AP1                             0.720820   
GDI1                                1.199272   
FAM50A                              0.720820   
FAM3A                               0.000000   
FUNDC2             

In [4]:
coord = pd.read_csv(f'{dir}/example_location.csv.gz', index_col=0)
coord

array_row  array_col
6800STDY12499411_AAACAAGTATCTCCCA-1         50        102
6800STDY12499411_AAACACCAATAACTGC-1         59         19
6800STDY12499411_AAACATGGTGAGAGGA-1         62          0
6800STDY12499411_AAACCGGGTAGGTACC-1         42         28
6800STDY12499411_AAACCGTTCGTCCAGG-1         52         42
...                                        ...        ...
6800STDY12499411_TTGTTCAGTGTGCTAC-1         24         64
6800STDY12499411_TTGTTGTGTGTCAAGA-1         31         77
6800STDY12499411_TTGTTTCACATCCAGG-1         58         42
6800STDY12499411_TTGTTTCATTAGTCTA-1         60         30
6800STDY12499411_TTGTTTCCATACAACT-1         45         27

[2048 rows x 2 columns]

In [5]:
skernel = spatialkernel(np.array(exprs), np.array(coord), bandwidthtype='silverman')
skernel

# The bandwidth is 0.1959 using silverman.


array([[1.00000000e+00, 7.48861782e-18, 8.89047919e-27, ...,
        7.29817216e-10, 5.95971163e-14, 2.35721001e-14],
       [7.48861782e-18, 1.00000000e+00, 1.15199728e-01, ...,
        5.37136480e-02, 5.04495952e-01, 1.42014137e-02],
       [8.89047919e-27, 1.15199728e-01, 1.00000000e+00, ...,
        4.52703200e-05, 6.60060470e-03, 5.78775794e-05],
       ...,
       [7.29817216e-10, 5.37136480e-02, 4.52703200e-05, ...,
        1.00000000e+00, 4.18865837e-01, 1.00455369e-02],
       [5.95971163e-14, 5.04495952e-01, 6.60060470e-03, ...,
        4.18865837e-01, 1.00000000e+00, 1.07810994e-02],
       [2.35721001e-14, 1.42014137e-02, 5.78775794e-05, ...,
        1.00455369e-02, 1.07810994e-02, 1.00000000e+00]])

In [6]:
isPD(skernel)

False

In [7]:
skernel_nearPD = nearestPD(skernel)
skernel_nearPD

array([[ 1.00000000e+00, -1.04696182e-14,  2.88887300e-15, ...,
         7.29817133e-10,  5.94009894e-14,  2.37400994e-14],
       [-1.04696182e-14,  1.00000000e+00,  1.15199728e-01, ...,
         5.37136480e-02,  5.04495952e-01,  1.42014137e-02],
       [ 2.88887300e-15,  1.15199728e-01,  1.00000000e+00, ...,
         4.52703200e-05,  6.60060470e-03,  5.78775794e-05],
       ...,
       [ 7.29817133e-10,  5.37136480e-02,  4.52703200e-05, ...,
         1.00000000e+00,  4.18865837e-01,  1.00455369e-02],
       [ 5.94009894e-14,  5.04495952e-01,  6.60060470e-03, ...,
         4.18865837e-01,  1.00000000e+00,  1.07810994e-02],
       [ 2.37400994e-14,  1.42014137e-02,  5.78775794e-05, ...,
         1.00455369e-02,  1.07810994e-02,  1.00000000e+00]])

In [8]:
chol_skernel = np.linalg.cholesky(skernel_nearPD)
chol_skernel

array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-1.04696182e-14,  1.00000000e+00,  0.00000000e+00, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 2.88887300e-15,  1.15199728e-01,  9.93342349e-01, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       ...,
       [ 7.29817133e-10,  5.37136480e-02, -6.18369620e-03, ...,
         2.90966109e-07,  0.00000000e+00,  0.00000000e+00],
       [ 5.94009894e-14,  5.04495952e-01, -5.18624739e-02, ...,
        -2.52998572e-09,  2.91120081e-07,  0.00000000e+00],
       [ 2.37400994e-14,  1.42014137e-02, -1.58869841e-03, ...,
        -5.18948584e-10,  1.77590290e-09,  3.06934120e-07]])

In [9]:
ori_skernel = chol_skernel @ chol_skernel.T
ori_skernel

array([[ 1.00000000e+00, -1.04696182e-14,  2.88887300e-15, ...,
         7.29817133e-10,  5.94009894e-14,  2.37400994e-14],
       [-1.04696182e-14,  1.00000000e+00,  1.15199728e-01, ...,
         5.37136480e-02,  5.04495952e-01,  1.42014137e-02],
       [ 2.88887300e-15,  1.15199728e-01,  1.00000000e+00, ...,
         4.52703200e-05,  6.60060470e-03,  5.78775794e-05],
       ...,
       [ 7.29817133e-10,  5.37136480e-02,  4.52703200e-05, ...,
         1.00000000e+00,  4.18865837e-01,  1.00455369e-02],
       [ 5.94009894e-14,  5.04495952e-01,  6.60060470e-03, ...,
         4.18865837e-01,  1.00000000e+00,  1.07810994e-02],
       [ 2.37400994e-14,  1.42014137e-02,  5.78775794e-05, ...,
         1.00455369e-02,  1.07810994e-02,  1.00000000e+00]])

In [10]:
np.round(skernel_nearPD, 6) == np.round(ori_skernel, 6)

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])